defaults: &defaults
  organ:
    system: 知一软件
  membership:
    member: 成员
    admin: 系统管理员
  domain: phonebook.zhiyisoft.com
  email_sender: 成都知一软件有限公司 <office@zhiyisoft.com>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults