defaults: &defaults
  system:
    - key: login_remember_day
      value: 5
      comment: 登陆记住天数

  user_properties:
    - 办公电话
    - 办公地址

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
