development:
  adapter: postgresql
  encoding: unicode
  database: phonebook_standalone
  pool: 5
  username: phonebook
  password: phonebook
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: phonebook_standalone
  pool: 5
  username: phonebook
  password: phonebook
  host: localhost
  port: 5432

production:
  adapter: postgresql
  encoding: unicode
  database: phonebook_standalone
  pool: 5
  username: phonebook
  password: phonebook
  host: localhost
  port: 5432
