sessions: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: phonebook
  password: phonebook
  host: localhost
  port: 5432

development:
  <<: *default
  database: phonebook_dev

test: &test
  <<: *default
  database: phonebook_test

production:
  <<: *default
  database: phonebook_pro

cucumber:
  <<: *test