development:
  adapter: postgresql
  encoding: utf8
  database: phonebook_dev
  username: phonebook
  password: phonebook
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: phonebook_test
  username: phonebook
  password: phonebook
  host: localhost

production:
  adapter: postgresql
  encoding: utf8
  database: phonebook_pro
  username: phonebook
  password: phonebook
  host: localhost
