server:
  - version:
      number: "0.01"
      description: "电话簿的基本管理功能"
  - version:
      number: "0.02"
      description: "电话簿的基本管理功能1"
client:
  - version:
      number: "0.02"
      download: "/public/soft/phonebook.apk"
      description: "按组织查询功能"
